projects:
  whatsappclone:
    schemaPath: src/graphql/schema.json
    includes:
      - 'Y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: .
